RDK-36812 : RPI Fix RDKMEDIAPLAYER build error in 64-bit
Reason for change: unsigned int to size_t error

| ../git/rdkmediaplayer.cpp:764:42: error: cast from 'RDKMediaPlayerImpl*' to 'uint32_t' {aka 'unsigned int'} loses precision [-fpermissive]
|   764 |         resp = (std::to_string((uint32_t)m_pImpl)).c_str();
|       |                                          ^~~~~~~
| ../git/rdkmediaplayer.cpp:785:51: error: cast from 'RDKMediaPlayerImpl*' to 'uint32_t' {aka 'unsigned int'} loses precision [-fpermissive]
|   785 |                 resp = (std::to_string((uint32_t)*it)).c_str();

Test Procedure: Build Images and do basic sanity
Risks: Low
Signed-off-by: Naveenkumar Hanasi <naveenkumar_hanasi@comcast.com>
(cherry picked from commit e6c805cc56ded258db6e33b69fda30d2a319900b)
(cherry picked from commit f54df176ec7674e7e3eed1f407de8b56673510ce)
Change-Id: I547568a9ba7e6091e22b1b0f566fac7de0aa6557